# Generated by Django 3.2.12 on 2022-03-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee_user',
        ),
    ]
