# Generated by Django 3.2.12 on 2022-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_assignee_user_id_issue_assignee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(max_length=64),
        ),
    ]
