# Generated by Django 4.0.2 on 2022-03-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_issue_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highlight',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
