# Generated by Django 3.2.12 on 2022-03-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_contributors_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'get_latest_by': ['-id']},
        ),
    ]
