# Generated by Django 4.0.2 on 2022-03-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highlight',
        ),
    ]
