# Generated by Django 3.2.12 on 2022-03-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220323_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_time']},
        ),
    ]
