# Generated by Django 3.2.12 on 2022-03-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220323_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'get_latest_by': ['created_time'], 'ordering': ['created_time']},
        ),
    ]
